/** Browser-only development preview. Simulated host observations are never runtime evidence. */
const http=require('node:http'),fs=require('node:fs'),path=require('node:path');
const {catalog}=require('../dist/catalog.js');const port=Number(process.env.PORT??4317);
const server=http.createServer((req,res)=>{
 if(req.url==='/state'){res.setHeader('Content-Type','application/json');res.end(JSON.stringify({catalog,observations:{'ext.fabric':{state:'detected',version:'sample',detail:'Preview fixture only.'}},workspace:{label:'sample-cloud-project (preview)',files:[{id:'f1-0',path:'functions/host.json',kind:'function'},{id:'f1-1',path:'model/tables/Sales.tmdl',kind:'model'},{id:'f1-2',path:'notebooks/ingest.ipynb',kind:'notebook'}],scan:'complete',notes:['Browser preview: observations are simulated.'],trusted:true,remote:false},favorites:[],presentation:'guided',checks:{},contextRevision:1}));return;}
 if(req.url==='/'){res.setHeader('Content-Type','text/html');res.end(`<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="stylesheet" href="/studio.css"><title>Cloud Studio - browser preview</title></head><body><div id="app"></div><script>
let s;window.previewMessages=[];window.acquireVsCodeApi=()=>({getState:()=>null,setState:()=>{},postMessage:async m=>{previewMessages.push(m);if(m.type==='ready'){s=await(await fetch('/state')).json();}if(m.type==='presentation')s.presentation=m.value;if(m.type==='favorite')s.favorites=s.favorites.includes(m.id)?s.favorites.filter(x=>x!==m.id):[...s.favorites,m.id];if(m.type==='check')s.checks[m.journey+'/'+m.route+'/'+m.index]=m.checked;if(s)window.postMessage({type:'state',state:s},'*');}});window.previewState=()=>s;
</script><script src="/studio.js"></script></body></html>`);return;}
 const name={'/studio.css':'studio.css','/studio.js':'studio.js'}[req.url];if(name){res.setHeader('Content-Type',name.endsWith('.css')?'text/css':'text/javascript');res.end(fs.readFileSync(path.join(__dirname,'../media',name)));}else{res.statusCode=404;res.end();}
});server.listen(port,'127.0.0.1',()=>console.log(`Preview only: http://127.0.0.1:${port}`));
