import { Catalog, Tool } from './core';
const MS = 'https://learn.microsoft.com/en-us/';
const GH = 'https://github.com/';
const date = '2026-09-26';
const tool = (t: Omit<Tool, 'checkedAt'>): Tool => ({ checkedAt: date, ...t });
/** Curated seed. Preserve shared DataPass tool IDs where available; no runtime dependency on it. */
export const catalog: Catalog = {
  tools: [
    tool({id:'ext.fabric', name:'Microsoft Fabric', kind:'extension', publisher:'Microsoft', studios:['fabric'], extensionId:'fabric.vscode-fabric', purpose:'Browse Fabric workspaces and items, open definitions and access the native Fabric experience.', notFor:'Not every workload-specific editor or a guarantee that a workspace is connected.', runsIn:'VS Code; live actions use Fabric', effects:['Native view may sign in or query Fabric. Item actions can modify cloud resources.'], docs:GH+'microsoft/vscode-fabric', cost:'Extension and service billing are separate. Fabric capacity and tenant permissions may be required.'}),
    tool({id:'ext.fabric-data-engineering', name:'Fabric Data Engineering', kind:'extension', publisher:'Microsoft', studios:['fabric'], extensionId:'SynapseVSCode.synapse', purpose:'Develop notebooks and Spark job definitions using the Fabric development workflow.', notFor:'A local notebook is not automatically connected to a Fabric runtime.', runsIn:'VS Code plus the configured local or Fabric runtime', effects:['Running notebooks executes code and may use paid compute.'], docs:MS+'fabric/data-engineering/author-notebook-with-vs-code', cost:'Compute is billed by the selected environment; installation is not capacity.'}),
    tool({id:'ext.fabric-studio', name:'Fabric Studio (community)', kind:'extension', publisher:'Community', studios:['fabric'], extensionId:'GerhardBrueckl.fabricstudio', purpose:'Browse Fabric, inspect definitions and use API notebooks through a community interface.', notFor:'Not the Microsoft Fabric extension or an MCP server.', runsIn:'VS Code and Fabric REST APIs', effects:['Publish and API notebook operations can write or delete cloud items.'], docs:GH+'gbrueckl/FabricStudio', cost:'Service consumption is separate from the extension.'}),
    tool({id:'ext.jupyter', name:'Jupyter', kind:'extension', publisher:'Microsoft', studios:['fabric'], extensionId:'ms-toolsai.jupyter', purpose:'Open notebook documents and choose an installed or remote kernel.', notFor:'Does not select the correct Fabric workspace or make execution safe.', runsIn:'Selected notebook kernel', effects:['Cell execution runs code; remote kernels have their own permissions.'], docs:'https://code.visualstudio.com/docs/datascience/jupyter-notebooks', cost:'Runtime/hosting costs depend on the kernel.'}),
    tool({id:'ext.python', name:'Python', kind:'extension', publisher:'Microsoft', studios:['fabric','azure'], extensionId:'ms-python.python', purpose:'Python editing, interpreter selection and test integration.', notFor:'A Python extension is not a Python interpreter or cloud runtime.', runsIn:'VS Code plus the selected interpreter', effects:['Tests and debugging execute project code.'], docs:'https://code.visualstudio.com/docs/python/python-tutorial', cost:'Runtime and cloud services are separate.'}),
    tool({id:'cli.python', name:'Python interpreter', kind:'cli', publisher:'Vendor', studios:['fabric','azure'], cli:'python', purpose:'Run Python code and tests in an explicitly chosen environment.', notFor:'A version probe does not verify project dependencies.', runsIn:'This extension host', effects:['Scripts execute with the selected environment and its access.'], docs:'https://code.visualstudio.com/docs/python/environments', cost:'Local execution uses your machine; external services may bill separately.'}),
    tool({id:'cli.fab', name:'Fabric CLI', kind:'cli', publisher:'Microsoft', studios:['fabric'], cli:'fab', purpose:'Use the Fabric command-line interface for supported management tasks.', notFor:'Not a replacement for notebook kernels or a universal validation engine.', runsIn:'Local process with Fabric access for live operations', effects:['Some commands change cloud state.'], docs:'https://microsoft.github.io/fabric-cli/', cost:'Fabric operations and compute retain their normal billing.'}),
    tool({id:'mcp.fabric', name:'Microsoft Fabric MCP', kind:'mcp', publisher:'Microsoft', studios:['fabric'], purpose:'Let a compatible agent use documented Fabric tools. Select the exact local or remote server first.', notFor:'Not the same as Azure MCP; transport, tools and sign-in depend on the server.', runsIn:'An explicitly configured MCP host', effects:['Tool results can reach the model provider. Some tools write remote or local state.'], docs:MS+'rest/api/fabric/articles/mcp/overview', cost:'Agent plan, MCP/service access and Fabric consumption are separate.'}),
    tool({id:'toolbox.fabric', name:'Fabric Toolbox', kind:'toolbox', publisher:'Microsoft', studios:['fabric'], purpose:'Choose individual CAT monitoring, CI/CD and operational samples for a specific need.', notFor:'Not one extension to install or a fully supported all-in-one platform.', runsIn:'Depends on the selected script, notebook, report or server', effects:['Some examples provision, write, delete or run billable workloads.'], docs:GH+'microsoft/fabric-toolbox', cost:'Each sample has its own infrastructure and runtime prerequisites.'}),
    tool({id:'lib.semantic-link-labs', name:'Semantic Link Labs', kind:'library', publisher:'Microsoft', studios:['fabric','powerbi'], purpose:'Use Python helpers in Fabric notebooks for semantic models, reports and platform analysis.', notFor:'Not a VS Code extension or an MCP server.', runsIn:'Fabric notebook / configured compatible runtime', effects:['Functions range from metadata reads to model and capacity changes.'], docs:GH+'microsoft/semantic-link-labs', cost:'Notebook execution can consume Fabric capacity.'}),
    tool({id:'ext.tmdl', name:'TMDL language support', kind:'extension', publisher:'Microsoft', studios:['powerbi'], extensionId:'analysis-services.TMDL', purpose:'Edit semantic model definitions in TMDL.', notFor:'Does not prove DAX results, report rendering or cloud deployment.', runsIn:'VS Code', effects:['Saving changes local definition files.'], docs:MS+'power-bi/developer/projects/projects-dataset', cost:'Model execution and Power BI licenses are separate.'}),
    tool({id:'app.pbi-desktop', name:'Power BI Desktop', kind:'desktop', publisher:'Microsoft', studios:['powerbi'], purpose:'Open, inspect and test a Power BI project and its report on Windows.', notFor:'Cloud Studio does not detect running Desktop instances or control its UI.', runsIn:'Windows desktop', effects:['Refresh can access data sources; publishing changes service content.'], docs:MS+'power-bi/developer/projects/projects-overview', cost:'Service publishing and sharing have separate license requirements.'}),
    tool({id:'ext.powerbi-modeling-mcp', name:'Power BI Authoring MCP', kind:'extension', publisher:'Microsoft', studios:['powerbi'], extensionId:'analysis-services.powerbi-modeling-mcp', purpose:'Expose semantic-model operations to a compatible agent: measures, tables, relationships and DAX.', notFor:'Does not edit report page layout. Installing the extension does not verify the agent connection.', runsIn:'MCP host and selected local or remote model', effects:['Can modify semantic models. Model metadata or data may reach the AI provider.'], docs:GH+'microsoft/powerbi-modeling-mcp', cost:'AI client, model access and cloud-service costs are separate.'}),
    tool({id:'plugin.powerbi-agentic', name:'Power BI Agentic (Microsoft)', kind:'agent-plugin', publisher:'Microsoft', studios:['powerbi'], purpose:'Use Microsoft authoring skills with a supported agent for models and report definitions.', notFor:'Not an independent runtime. Host compatibility and enabled skills must be checked.', runsIn:'The selected supported AI host', effects:['Agent tools can modify files or models; review scope and data handling.'], docs:MS+'power-bi/developer/agentic/power-bi-agentic-overview', cost:'Requires the chosen agent plan and any underlying service access.'}),
    tool({id:'plugin.data-goblin', name:'Power BI agentic development', kind:'agent-plugin', publisher:'Community', studios:['powerbi','fabric'], purpose:'Select data-goblin skills, agents and hooks for PBIP, reports, models or Fabric work.', notFor:'Not one plugin and not an automatic MCP connection. Do not install every plugin.', runsIn:'Claude Code or other documented compatible hosts', effects:['Hooks and scripts may run automatically once installed. Pin reviewed versions.'], docs:GH+'data-goblin/power-bi-agentic-development', cost:'Agent usage is separate. Review upstream licenses before redistributing assets.'}),
    tool({id:'ext.azure-resources', name:'Azure Resources', kind:'extension', publisher:'Microsoft', studios:['azure'], extensionId:'ms-azuretools.vscode-azureresourcegroups', purpose:'Use the Azure account and resource experience shared by Azure extensions.', notFor:'Resource visibility does not prove permission for a particular action.', runsIn:'VS Code and Azure', effects:['Native views may sign in and query account metadata.'], docs:'https://code.visualstudio.com/docs/azure/overview', cost:'Cloud resource charges are independent of the extension.'}),
    tool({id:'ext.azure-functions', name:'Azure Functions', kind:'extension', publisher:'Microsoft', studios:['azure'], extensionId:'ms-azuretools.vscode-azurefunctions', purpose:'Develop, debug and publish Function Apps through the native extension.', notFor:'Publishing is not a read-only test and can replace an existing Function App deployment.', runsIn:'VS Code, Core Tools and the selected Function App', effects:['Local functions can access real services; publishing writes cloud state.'], docs:MS+'azure/azure-functions/functions-develop-vs-code', cost:'Azure execution, storage and monitoring may be billable.'}),
    tool({id:'cli.func', name:'Functions Core Tools', kind:'cli', publisher:'Microsoft', studios:['azure'], cli:'func', purpose:'Run and inspect Azure Functions development tooling.', notFor:'A successful version check does not prove the app starts or dependencies are installed.', runsIn:'This extension host', effects:['func start executes code and may consume real events.'], docs:MS+'azure/azure-functions/functions-core-tools-reference', cost:'Local hosting can still call paid cloud services.'}),
    tool({id:'cli.az', name:'Azure CLI', kind:'cli', publisher:'Microsoft', studios:['azure'], cli:'az', purpose:'Use supported Azure management commands with an explicitly selected identity and target.', notFor:'Cloud Studio only probes its version; it does not read sign-in tokens or account state.', runsIn:'This extension host', effects:['Commands can provision, delete, change access or return sensitive values.'], docs:MS+'cli/azure/', cost:'Resource and service consumption are billed independently.'}),
    tool({id:'ext.azure-storage', name:'Azure Storage', kind:'extension', publisher:'Microsoft', studios:['azure'], extensionId:'ms-azuretools.vscode-azurestorage', purpose:'Use the native Storage explorer for accounts, containers and objects.', notFor:'Not a document evidence registry or a PDF extractor.', runsIn:'VS Code and Azure Storage', effects:['Upload, download and delete have data-access and billing consequences.'], docs:GH+'microsoft/vscode-azurestorage', cost:'Storage, transactions and transfer may be billable.'}),
    tool({id:'ext.cosmosdb', name:'Azure Databases / Cosmos DB', kind:'extension', publisher:'Microsoft', studios:['azure'], extensionId:'ms-azuretools.vscode-cosmosdb', purpose:'Use the Azure database extension for supported Cosmos operations.', notFor:'Not the MongoDB Atlas client; database APIs differ.', runsIn:'VS Code and the selected database', effects:['Queries may read sensitive data; writes modify persistent records.'], docs:GH+'microsoft/vscode-cosmosdb', cost:'Database throughput and storage are service costs.'}),
    tool({id:'cli.node', name:'Node.js', kind:'cli', publisher:'Vendor', studios:['azure'], cli:'node', purpose:'Run JavaScript development tools such as the ADF utilities package.', notFor:'A system version is not evidence that a project package is installed.', runsIn:'This extension host', effects:['Running project scripts executes code.'], docs:'https://code.visualstudio.com/docs/nodejs/nodejs-tutorial', cost:'Local execution; called services retain their charges.'}),
    tool({id:'tool.adf-utilities', name:'Azure Data Factory utilities', kind:'library', publisher:'Microsoft', studios:['azure'], purpose:'Use Microsoft validation and ARM export logic in an explicit build step.', notFor:'Not Fabric Data Factory. ARM export is not deployment.', runsIn:'A prepared Node.js project or CI job', effects:['Runs package/project tooling and can create build outputs.'], docs:MS+'azure/data-factory/continuous-integration-delivery-improvements', cost:'Build-agent and any connected-service costs are separate.'}),
    tool({id:'ref.unified-data-foundation', name:'Unified Data Foundation', kind:'reference', publisher:'Microsoft', studios:['fabric','azure'], purpose:'Study a reference architecture with Fabric and optional Purview or Azure Databricks.', notFor:'Not a prerequisite for using Cloud Studio or MCP.', runsIn:'A separately reviewed deployment', effects:['Deployment may create billable services and permissions.'], docs:GH+'microsoft/unified-data-foundation-with-fabric-solution-accelerator', cost:'Fabric, Databricks and Purview costs depend on selected components.'}),
    tool({id:'ref.fabric-capacity-iac', name:'Fabric capacity IaC examples', kind:'reference', publisher:'Community', studios:['azure','fabric'], purpose:'Inspect Terraform, Bicep and ARM examples for a Fabric capacity.', notFor:'Not notebook execution or a free-capacity entitlement.', runsIn:'A reviewed IaC workflow', effects:['Apply/deployment creates or changes billable infrastructure. Review the plan; do not copy auto-approve as a default.'], docs:GH+'murggu/fabric-capacity-iac', cost:'Fabric capacity billing applies after provisioning.'})
  ],
  journeys: [
    {
      id:'fabric.open-item', studio:'fabric', title:'Open and understand a Fabric item', description:'Find the right editor for a workspace item without confusing local files with the live service.', artifact:'Workspace item / local definition', minutes:'5-10 min', matches:['fabric-item','notebook'],
      outcome:'The intended item is open in its native tool; its local-versus-remote state is understood.',
      boundaries:['Browsing can contact Fabric and prompt for authentication.','Do not import, publish, delete or change permissions as part of this journey.'],
      checks:['Confirm the tenant and workspace in the native tool.','Confirm the selected item and whether the definition is local or remote.','Record any pending local changes before switching workflows.'], docs:GH+'microsoft/vscode-fabric',
      routes:[
        {id:'native',label:'Native tools',summary:'Start with the official Fabric extension. Community Fabric Studio remains an explicit alternative.',tools:['ext.fabric'],steps:[
          {title:'Choose the working folder',body:'Use the folder selector above for a local project. No folder is required to browse the native Fabric service.'},
          {title:'Open Microsoft Fabric',body:'Open its native view, sign in there if necessary and choose the correct workspace. Cloud Studio does not own authentication.',action:'tool',toolId:'ext.fabric'},
          {title:'Inspect local definitions',body:'Open any detected .platform or notebook file as source. Their presence is not deployment proof.',action:'files'},
          {title:'Check the item workflow',body:'Read the official item workflow before exporting or publishing definitions.',action:'docs'}]},
        {id:'ai',label:'Agent-assisted',summary:'Use a documented Fabric MCP server for a bounded discovery task. Connection and credentials stay in your chosen client.',tools:['mcp.fabric'],steps:[
          {title:'Choose the correct server',body:'Distinguish Fabric Core, local development and workload-specific servers. Check transport and authentication compatibility.',action:'tool',toolId:'mcp.fabric'},
          {title:'Review host configuration',body:'Open native VS Code MCP settings for Copilot. Other clients require their own configuration.',action:'mcp'},
          {title:'Ask for metadata only',body:'Use Preview context for AI. Specify the exact workspace in the approved agent session; prohibit create/update/delete operations.'}]}
      ]
    },
    {
      id:'fabric.notebook',studio:'fabric',title:'Prepare a Fabric notebook',description:'Open a notebook and establish the correct interpreter, workspace and execution route before running it.',artifact:'Notebook / Spark job',minutes:'10-15 min',matches:['notebook','fabric-item','code'],outcome:'The source is open and a runtime is deliberately selected; execution is still a separate action.',
      boundaries:['Opening a notebook is not running it.','Kernel or Fabric execution may read/write data and consume capacity.'],checks:['Confirm the native notebook and intended Fabric workspace.','Confirm its lakehouse and environment dependencies.','Use a safe sample before running transformations on real data.'],docs:MS+'fabric/data-engineering/author-notebook-with-vs-code',
      routes:[{id:'native',label:'Native tools',summary:'Use the Fabric Data Engineering workflow, with Python and Jupyter when required by the selected path.',tools:['ext.fabric-data-engineering','ext.python','ext.jupyter'],steps:[
        {title:'Inspect notebook source',body:'Open the detected notebook as text alongside this guide. Use VS Code Reopen Editor With to select its native notebook editor.',action:'files'},
        {title:'Check the development extension',body:'Open its extension page/native view and follow the matching setup instructions.',action:'tool',toolId:'ext.fabric-data-engineering'},
        {title:'Select runtime deliberately',body:'Local Jupyter, local Spark and Fabric remote execution are different routes. Do not infer a runtime from the file extension.',action:'docs'},
        {title:'Prepare a small test',body:'Review cells and dependencies. The native editor owns any actual Run or Publish action.'}]}]
    },
    {
      id:'powerbi.pbip',studio:'powerbi',title:'Understand a Power BI project',description:'Separate the semantic model, report definitions and published service before editing a PBIP project.',artifact:'PBIP / TMDL / PBIR',minutes:'5-10 min',matches:['pbip','model','report'],outcome:'You can identify the model files, report definition and native verification tool.',boundaries:['Cloud Studio does not parse or execute DAX or render the report.','Do not move or rename model objects simply to improve the file tree.'],checks:['Locate the PBIP entry and its report/model folders.','Confirm which files belong to the semantic model versus the report.','Open a copy in Desktop to verify the report before publishing.'],docs:MS+'power-bi/developer/projects/projects-overview',
      routes:[{id:'native',label:'Native tools',summary:'Read native source files, use TMDL language support and verify the project in Power BI Desktop.',tools:['ext.tmdl','app.pbi-desktop'],steps:[
        {title:'Explore native definitions',body:'Choose the PBIP, .tmdl or definition.pbir file. Open it beside the guide without running anything.',action:'files'},
        {title:'Set up TMDL editing',body:'Use the native language extension for model definitions. It is not a DAX correctness checker.',action:'tool',toolId:'ext.tmdl'},
        {title:'Verify the project in Desktop',body:'Open the project in Power BI Desktop on Windows. This Studio does not detect or launch Desktop automatically.',action:'tool',toolId:'app.pbi-desktop'}]}]
    },
    {
      id:'powerbi.document-model',studio:'powerbi',title:'Document measures without changing logic',description:'Prepare scoped measure documentation on a copy of a model while preserving formulas, types, field parameters and relationships.',artifact:'Semantic model',minutes:'10-15 min',matches:['pbip','model'],outcome:'A reviewed change containing descriptions only, with native model and report checks.',boundaries:['Use a copy or branch, never an unreviewed production model.','Change descriptions only; do not change DAX, types, field parameters, names or relationships.','MCP results may be sent to the selected model provider.'],checks:['Review a diff and confirm that only authorized description properties changed.','Check representative measures and field parameters in the native tool.','Open the report and check that visuals still work.'],docs:MS+'power-bi/developer/mcp/power-bi-authoring-mcp',
      routes:[{id:'native',label:'Native files',summary:'Edit descriptions in TMDL and verify in Desktop. No AI required.',tools:['ext.tmdl','app.pbi-desktop'],steps:[
        {title:'Start from a safe copy',body:'Create a branch or backup using your normal Git/Desktop workflow. Cloud Studio does not make one for you.'},
        {title:'Open model definitions',body:'Edit the existing description properties; do not change formulas or object identity.',action:'files'},
        {title:'Review and verify',body:'Use the native Git diff and open the project in Desktop. A saved file is not a verified model.',action:'tool',toolId:'app.pbi-desktop'}]},
      {id:'ai',label:'Agent-assisted',summary:'Prepare a narrowly scoped prompt for a compatible Power BI Authoring MCP client.',tools:['ext.powerbi-modeling-mcp','plugin.powerbi-agentic'],steps:[
        {title:'Choose the model and client',body:'Use a disposable copy. Choose local Desktop/PBIP or hosted authoring as documented; do not assume equivalent connection support.',action:'tool',toolId:'ext.powerbi-modeling-mcp'},
        {title:'Review MCP setup',body:'Confirm tools and permissions in the actual AI client. VS Code MCP settings apply to its native host, not automatically to Codex or Claude.',action:'mcp'},
        {title:'Preview bounded context',body:'Use Preview context for AI and inspect it before copying. Ask for a proposed diff before allowing description edits.'},
        {title:'Verify independently',body:'Review the real file/model diff. A successful tool call is not model or report validation.'}]}]
    },
    {
      id:'azure.function',studio:'azure',title:'Prepare a Function for a local test',description:'Inspect a Function App root and prepare native tooling without accidentally consuming production events.',artifact:'Azure Function App',minutes:'10-15 min',matches:['function','code','infra'],outcome:'A reviewed local-test plan for the right app root, interpreter and isolated connections.',boundaries:['local.settings.json is never included in Cloud Studio scans or AI context.','func start runs code and may connect to real event sources.','Do not publish in this journey; publishing can replace the existing app deployment.'],checks:['Confirm the app root and programming model.','Confirm the selected interpreter and dependencies.','Use isolated storage/event sources; inspect any trigger before starting.','Review local output in the native tool; do not mark a cloud deployment verified.'],docs:MS+'azure/azure-functions/functions-develop-vs-code',
      routes:[{id:'native',label:'Native tools',summary:'Use Azure Functions, its Core Tools and the native Python tooling when this is a Python app.',tools:['ext.azure-functions','cli.func'],steps:[
        {title:'Inspect the app files',body:'Open host.json and the entry function. Other programming models are valid; this guide does not assume function_app.py is required for all apps.',action:'files'},
        {title:'Check Core Tools',body:'Copy the version command, or use Check CLI versions. Nothing here starts a host.',action:'copy',copy:'func --version'},
        {title:'Open Azure Functions',body:'Use the native extension to select the app and interpreter. Review the local connections outside Cloud Studio.',action:'tool',toolId:'ext.azure-functions'},
        {title:'Run only after reviewing triggers',body:'Follow the native local-development guide. The actual start/debug action remains in the official tool.',action:'docs'}]}]
    },
    {
      id:'azure.adf',studio:'azure',title:'Prepare Azure Data Factory validation',description:'Locate an ADF Git folder and prepare the native validation route without publishing the factory.',artifact:'ADF pipeline / linked service',minutes:'10-15 min',matches:['adf'],outcome:'A reproducible validation plan for the right folder and factory resource ID, not a deployment.',boundaries:['Azure Data Factory and Fabric Data Factory are distinct products.','Do not export secrets or connection strings in context.','Running a package is code execution; installing or publishing remains a separate approval.'],checks:['Confirm this is Azure Data Factory Git-format source.','Check the root and intended factory ID with the owner.','Run the documented Validate action or prepared CI utility and inspect its real output.','Do not confuse ARM export with deployment or pipeline runtime validation.'],docs:MS+'azure/data-factory/continuous-integration-delivery-improvements',
      routes:[{id:'native',label:'Native tools',summary:'Choose ADF Studio Validate all or a reviewed CI job using the Microsoft utilities package.',tools:['cli.node','tool.adf-utilities'],steps:[
        {title:'Locate ADF source',body:'Inspect pipeline, dataset, linkedService and trigger definitions. An absent local clone is not proof that a remote factory is missing.',action:'files'},
        {title:'Read the supported utility workflow',body:'The official guide specifies Node compatibility, package preparation and the factory resource ID. It provides validation and ARM export, not automatic deployment.',action:'tool',toolId:'tool.adf-utilities'},
        {title:'Inspect the Node version',body:'Check the version before using the supported package workflow. This does not install or execute a project dependency.',action:'copy',copy:'node --version'},
        {title:'Use the native validator',body:'Open ADF Studio or your approved CI job and run validation there. Cloud Studio v0.1 prepares the route; it does not claim to execute ADF validation.',action:'docs'}]}]
    }
  ]
};
